// ============================================================
// NodeRed.Nodes.Core Tests
// Tests for core nodes translation
// ============================================================

using System.Text.Json;
using NodeRed.Nodes.Core;
using NodeRed.Nodes.Core.Common;
using NodeRed.Nodes.Core.Function;
using NodeRed.Nodes.Core.Parsers;
using NodeRed.Nodes.Core.Sequence;
using NodeRed.Nodes.Core.Storage;
using Xunit;

namespace NodeRed.Nodes.Core.Tests;

#region Base Node Tests
public class BaseNodeTests
{
    [Fact]
    public void FlowMessage_Clone_CreatesCopy()
    {
        var msg = new FlowMessage
        {
            Payload = "test",
            Topic = "topic1"
        };
        
        var clone = msg.Clone();
        
        Assert.Equal("test", clone.Payload?.ToString());
        Assert.Equal("topic1", clone.Topic);
        Assert.NotEqual(msg, clone);
    }
    
    [Fact]
    public void FlowMessage_HasAutoGeneratedMsgId()
    {
        var msg1 = new FlowMessage();
        var msg2 = new FlowMessage();
        
        Assert.NotNull(msg1.MsgId);
        Assert.NotNull(msg2.MsgId);
        Assert.NotEqual(msg1.MsgId, msg2.MsgId);
    }
    
    [Fact]
    public void NodeTypeRegistry_RegisterAndGetType()
    {
        // Clear and register
        NodeTypeRegistry.RegisterType("test-node", config => new TestNode(config));
        
        var types = NodeTypeRegistry.GetAllTypes();
        Assert.Contains("test-node", types);
    }
    
    [Fact]
    public void NodeTypeRegistry_CreateNode()
    {
        NodeTypeRegistry.RegisterType("create-test", config => new TestNode(config));
        
        var config = new NodeConfig { Id = "n1", Type = "create-test" };
        var node = NodeTypeRegistry.CreateNode("create-test", config);
        
        Assert.NotNull(node);
        Assert.Equal("n1", node.Id);
    }
    
    private class TestNode : BaseNode
    {
        public TestNode(NodeConfig config) : base(config)
        {
        }
    }
}
#endregion

#region Inject Node Tests
public class InjectNodeTests
{
    [Fact]
    public async Task InjectNode_SendsMessage()
    {
        InjectNode.Register();
        
        var config = new InjectNodeConfig
        {
            Id = "inject1",
            Type = "inject",
            Payload = "test payload",
            PayloadType = "str"
        };
        
        var node = new InjectNode(config);
        FlowMessage? receivedMsg = null;
        
        node.MessageSent += (s, msg) =>
        {
            if (msg is FlowMessage flowMsg)
                receivedMsg = flowMsg;
        };
        
        await node.ReceiveAsync(new FlowMessage());
        
        Assert.NotNull(receivedMsg);
        Assert.Equal("test payload", receivedMsg!.Payload?.ToString());
    }
    
    [Fact]
    public async Task InjectNode_DatePayload()
    {
        var config = new InjectNodeConfig
        {
            Id = "inject2",
            Type = "inject",
            PayloadType = "date"
        };
        
        var node = new InjectNode(config);
        FlowMessage? receivedMsg = null;
        
        node.MessageSent += (s, msg) =>
        {
            if (msg is FlowMessage flowMsg)
                receivedMsg = flowMsg;
        };
        
        var before = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();
        await node.ReceiveAsync(new FlowMessage());
        var after = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();
        
        Assert.NotNull(receivedMsg);
        var timestamp = Convert.ToInt64(receivedMsg!.Payload);
        Assert.InRange(timestamp, before, after);
    }
}
#endregion

#region Debug Node Tests
public class DebugNodeTests
{
    [Fact]
    public async Task DebugNode_RaisesDebugEvent()
    {
        DebugNode.Register();
        
        var config = new DebugNodeConfig
        {
            Id = "debug1",
            Type = "debug",
            ToSidebar = true
        };
        
        var node = new DebugNode(config);
        DebugMessage? receivedDebug = null;
        
        DebugNode.DebugMessageReceived += (s, msg) =>
        {
            receivedDebug = msg;
        };
        
        await node.ReceiveAsync(new FlowMessage { Payload = "debug test" });
        
        Assert.NotNull(receivedDebug);
        Assert.Equal("debug test", receivedDebug!.Msg?.ToString());
    }
    
    [Fact]
    public void DebugNode_ActiveState()
    {
        var config = new DebugNodeConfig
        {
            Id = "debug2",
            Type = "debug",
            Active = true
        };
        
        var node = new DebugNode(config);
        Assert.True(node.IsActive);
        
        node.SetActive(false);
        Assert.False(node.IsActive);
    }
}
#endregion

#region Switch Node Tests
public class SwitchNodeTests
{
    [Fact]
    public async Task SwitchNode_EqualityRule()
    {
        SwitchNode.Register();
        
        var config = new SwitchNodeConfig
        {
            Id = "switch1",
            Type = "switch",
            Property = "payload",
            PropertyType = "msg",
            Rules = new List<SwitchRule>
            {
                new SwitchRule { Type = "eq", Value = "hello", ValueType = "str" }
            }
        };
        
        var node = new SwitchNode(config);
        List<object?> outputs = new();
        
        node.MessageSent += (s, msg) =>
        {
            outputs.Add(msg);
        };
        
        await node.ReceiveAsync(new FlowMessage { Payload = "hello" });
        
        Assert.Single(outputs);
    }
    
    [Fact]
    public async Task SwitchNode_NumericComparison()
    {
        var config = new SwitchNodeConfig
        {
            Id = "switch2",
            Type = "switch",
            Property = "payload",
            Rules = new List<SwitchRule>
            {
                new SwitchRule { Type = "gt", Value = "10", ValueType = "num" }
            }
        };
        
        var node = new SwitchNode(config);
        List<object?> outputs = new();
        
        node.MessageSent += (s, msg) =>
        {
            outputs.Add(msg);
        };
        
        await node.ReceiveAsync(new FlowMessage { Payload = 15 });
        
        Assert.Single(outputs);
    }
}
#endregion

#region Change Node Tests
public class ChangeNodeTests
{
    [Fact]
    public async Task ChangeNode_SetProperty()
    {
        ChangeNode.Register();
        
        var config = new ChangeNodeConfig
        {
            Id = "change1",
            Type = "change",
            Rules = new List<ChangeRule>
            {
                new ChangeRule { Type = "set", Property = "payload", To = "new value", ToType = "str" }
            }
        };
        
        var node = new ChangeNode(config);
        FlowMessage? output = null;
        
        node.MessageSent += (s, msg) =>
        {
            if (msg is FlowMessage flowMsg)
                output = flowMsg;
        };
        
        await node.ReceiveAsync(new FlowMessage { Payload = "old value" });
        
        Assert.NotNull(output);
        Assert.Equal("new value", output!.Payload?.ToString());
    }
    
    [Fact]
    public async Task ChangeNode_DeleteProperty()
    {
        var config = new ChangeNodeConfig
        {
            Id = "change2",
            Type = "change",
            Rules = new List<ChangeRule>
            {
                new ChangeRule { Type = "delete", Property = "payload" }
            }
        };
        
        var node = new ChangeNode(config);
        FlowMessage? output = null;
        
        node.MessageSent += (s, msg) =>
        {
            if (msg is FlowMessage flowMsg)
                output = flowMsg;
        };
        
        await node.ReceiveAsync(new FlowMessage { Payload = "to delete" });
        
        Assert.NotNull(output);
        Assert.Null(output!.Payload);
    }
}
#endregion

#region JSON Node Tests
public class JsonNodeTests
{
    [Fact]
    public async Task JsonNode_ParseString()
    {
        JsonNode.Register();
        
        var config = new JsonNodeConfig
        {
            Id = "json1",
            Type = "json",
            Action = "obj"
        };
        
        var node = new JsonNode(config);
        FlowMessage? output = null;
        
        node.MessageSent += (s, msg) =>
        {
            if (msg is FlowMessage flowMsg)
                output = flowMsg;
        };
        
        await node.ReceiveAsync(new FlowMessage { Payload = "{\"key\":\"value\"}" });
        
        Assert.NotNull(output);
        Assert.IsType<JsonElement>(output!.Payload);
    }
    
    [Fact]
    public async Task JsonNode_StringifyObject()
    {
        var config = new JsonNodeConfig
        {
            Id = "json2",
            Type = "json",
            Action = "str"
        };
        
        var node = new JsonNode(config);
        FlowMessage? output = null;
        
        node.MessageSent += (s, msg) =>
        {
            if (msg is FlowMessage flowMsg)
                output = flowMsg;
        };
        
        var obj = new { key = "value" };
        await node.ReceiveAsync(new FlowMessage { Payload = obj });
        
        Assert.NotNull(output);
        Assert.IsType<string>(output!.Payload);
        Assert.Contains("key", output.Payload.ToString());
    }
}
#endregion

#region Range Node Tests
public class RangeNodeTests
{
    [Fact]
    public async Task RangeNode_ScalesValue()
    {
        RangeNode.Register();
        
        var config = new RangeNodeConfig
        {
            Id = "range1",
            Type = "range",
            MinIn = 0,
            MaxIn = 100,
            MinOut = 0,
            MaxOut = 10,
            Action = "scale"
        };
        
        var node = new RangeNode(config);
        FlowMessage? output = null;
        
        node.MessageSent += (s, msg) =>
        {
            if (msg is FlowMessage flowMsg)
                output = flowMsg;
        };
        
        await node.ReceiveAsync(new FlowMessage { Payload = 50 });
        
        Assert.NotNull(output);
        Assert.Equal(5.0, Convert.ToDouble(output!.Payload));
    }
}
#endregion

#region Split Node Tests
public class SplitNodeTests
{
    [Fact]
    public async Task SplitNode_SplitsString()
    {
        SplitNode.Register();
        
        var config = new SplitNodeConfig
        {
            Id = "split1",
            Type = "split",
            Splt = ",",
            SpltType = "str"
        };
        
        var node = new SplitNode(config);
        List<FlowMessage> outputs = new();
        
        node.MessageSent += (s, msg) =>
        {
            if (msg is FlowMessage flowMsg)
                outputs.Add(flowMsg);
        };
        
        await node.ReceiveAsync(new FlowMessage { Payload = "a,b,c" });
        
        Assert.Equal(3, outputs.Count);
        Assert.Equal("a", outputs[0].Payload?.ToString());
        Assert.Equal("b", outputs[1].Payload?.ToString());
        Assert.Equal("c", outputs[2].Payload?.ToString());
    }
}
#endregion

#region Delay Node Tests
public class DelayNodeTests
{
    [Fact]
    public async Task DelayNode_DelaysMessage()
    {
        DelayNode.Register();
        
        var config = new DelayNodeConfig
        {
            Id = "delay1",
            Type = "delay",
            PauseType = "delay",
            Timeout = 0.1, // 100ms
            TimeoutUnits = "seconds"
        };
        
        var node = new DelayNode(config);
        FlowMessage? output = null;
        
        node.MessageSent += (s, msg) =>
        {
            if (msg is FlowMessage flowMsg)
                output = flowMsg;
        };
        
        var start = DateTime.UtcNow;
        await node.ReceiveAsync(new FlowMessage { Payload = "delayed" });
        var elapsed = DateTime.UtcNow - start;
        
        Assert.NotNull(output);
        Assert.True(elapsed.TotalMilliseconds >= 90); // Allow some tolerance
    }
}
#endregion

#region Template Node Tests
public class TemplateNodeTests
{
    [Fact]
    public async Task TemplateNode_RendersTemplate()
    {
        TemplateNode.Register();
        
        var config = new TemplateNodeConfig
        {
            Id = "template1",
            Type = "template",
            Template = "Hello {{payload}}!",
            Syntax = "mustache"
        };
        
        var node = new TemplateNode(config);
        FlowMessage? output = null;
        
        node.MessageSent += (s, msg) =>
        {
            if (msg is FlowMessage flowMsg)
                output = flowMsg;
        };
        
        await node.ReceiveAsync(new FlowMessage { Payload = "World" });
        
        Assert.NotNull(output);
        Assert.Equal("Hello World!", output!.Payload?.ToString());
    }
}
#endregion

#region Registration Tests
public class CoreNodesRegistrationTests
{
    [Fact]
    public void RegisterAll_RegistersAllNodes()
    {
        CoreNodesRegistration.RegisterAll();
        
        var types = NodeTypeRegistry.GetAllTypes().ToList();
        
        // Check common nodes
        Assert.Contains("inject", types);
        Assert.Contains("debug", types);
        Assert.Contains("catch", types);
        Assert.Contains("complete", types);
        
        // Check function nodes
        Assert.Contains("function", types);
        Assert.Contains("switch", types);
        Assert.Contains("change", types);
        Assert.Contains("delay", types);
        
        // Check parser nodes
        Assert.Contains("json", types);
        Assert.Contains("csv", types);
        Assert.Contains("xml", types);
        
        // Check sequence nodes
        Assert.Contains("split", types);
        Assert.Contains("join", types);
        Assert.Contains("sort", types);
    }
    
    [Fact]
    public void GetNodeSummary_ReturnsDescriptions()
    {
        var summary = CoreNodesRegistration.GetNodeSummary();
        
        Assert.NotEmpty(summary);
        Assert.True(summary.ContainsKey("inject"));
        Assert.True(summary.ContainsKey("debug"));
        Assert.Contains("trigger", summary["inject"].ToLower());
    }
}
#endregion
